name: 'Deploy to GitHub Pages'

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: ddanijel

      - name: Build
        run: |
          yarn install
          build build
        env:
          REACT_APP_INFURA_REMOTE_CLIENT_URL: ${{ secrets.REACT_APP_INFURA_REMOTE_CLIENT_URL }}

      - name: Deploy
        uses: ddanijel
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build